create go routing with new handler
BawNer/go-shortener-tpl pull request #14
Opened 2022-12-14 09:33 UTC by BawNer

2022-12-18 07:03 UTC, shmel1k requested changes

2022-12-18 07:03 UTC, shmel1k commented on internal/app/handlers/delete_batch.go
> +	for {
А почему здесь бесконечный цикл?

2022-12-22 10:59 UTC, shmel1k requested changes

2022-12-22 10:59 UTC, shmel1k commented on cmd/shortener/main.go
> +	}
Я бы утащил это из main и в стородже сделал что-то типа метода `RunWorkers()`, который под капотом делал бы примерно это же

2022-12-22 10:59 UTC, shmel1k commented on cmd/shortener/main.go
> +	}
Я показывал пример того, как это может выглядеть, где-то в чатах. Кажется, это было в жирном треде про рейсы

2022-12-22 10:59 UTC, shmel1k commented on cmd/shortener/main.go
> +	if err := server.Shutdown(context.Background()); err != nil {
Я бы предложил сперва завершать сервер. Потому что воркерпул уже встанет, а все остальные запросы будут завершаться 500кой или чем ещё хуже

2022-12-22 15:10 UTC, BawNer commented on cmd/shortener/main.go
> +	if err := server.Shutdown(context.Background()); err != nil {
обновил

2022-12-25 19:42 UTC, shmel1k requested changes

2022-12-25 19:42 UTC, shmel1k commented on cmd/shortener/main.go
> +			log.Fatal(err.Error())
Можно просто log.Fatal(err)

2022-12-25 19:42 UTC, shmel1k commented on cmd/shortener/main.go
> +	log.Printf("Channel has been closed")
Плохая практика to mix комментарии in английский энд in russian)

Лучше придерживаться именно одного языка(предпочтительно -- англ)

2022-12-25 19:42 UTC, shmel1k commented on internal/app/config.go
> +		defaultWorkers         = 3
лучше `defaultWorkersCount`

2022-12-25 19:42 UTC, shmel1k commented on internal/app/handlers/shorten_batch.go
> +			IsDeleted: false,
Можно не проставлять явно, но вот здесь явное проставление играет на руку: удобнее читать

2022-12-25 19:42 UTC, shmel1k commented on internal/app/storage/database/postgres.go
> +		log.Println(err)
Лучше дополнить сообщение чем-то

например
```go
log.Printf("failed to delete url: %s", err)
```
а выше -- `failed to perform query deletion`

2022-12-25 19:42 UTC, shmel1k commented on internal/app/storage/storage.go
> +	InputCh chan DataForWorker
Это явно не "Repository". Лучше вытащить это в отдельный пакет с названием `pool` или `workerpool`. 
Будет что-то типа
```go
type WorkerPool struct {
   ...
}

func (w *WorkerPool) AddJob(f func() error) error {

}
```
ну или как-то так.

и тот же принцип, что в примере из огромного треда

2022-12-25 20:14 UTC, BawNer commented on cmd/shortener/main.go
> +			log.Fatal(err.Error())
+

2022-12-25 20:15 UTC, BawNer commented on cmd/shortener/main.go
> +	log.Printf("Channel has been closed")
+

2022-12-25 20:15 UTC, BawNer commented on internal/app/config.go
> +		defaultWorkers         = 3
+

2022-12-25 20:18 UTC, BawNer commented on internal/app/storage/database/postgres.go
> +		log.Println(err)
+

2022-12-26 05:44 UTC, shmel1k requested changes

2022-12-26 05:44 UTC, shmel1k commented on internal/app/config.go
> +	Workers         int
И тут лучше WorkersCount

2022-12-26 05:44 UTC, shmel1k commented on internal/app/handlers/data.go
> +func NewHandler(repository storage.Storage, worker *workerpool.WorkerPool) *Handler {
Или workers, или pool или `workerPool`

`worker *workerpool.WorkerPool` не отражает суть того, что это пул

2022-12-26 05:44 UTC, shmel1k commented on internal/app/workerpool/manager.go
> +	down    chan struct{}
Вот тут не очень удачное название

Лучше `stop`, `done`, `exiting`, `shuttingDown`. `Down` - это когда уже потушен, но чтение из этого канала будет не в момент, когда "потушен", а в момент, когда "завершаемся"

2022-12-26 05:44 UTC, shmel1k commented on internal/app/workerpool/manager.go
> +	down    chan struct{}
Вот тут не очень удачное название

Лучше `stop`, `done`, `exiting`, `shuttingDown`. `Down` - это когда уже потушен, но чтение из этого канала будет не в момент, когда "потушен", а в момент, когда "завершаемся"

2022-12-26 05:44 UTC, shmel1k commented on internal/app/workerpool/manager.go
> +		return ErrRepositoryIsClosing
Нужно переименовать на что-то типа `ErrShuttingDown` или как-то так. Репозитория здесь уже нет

2022-12-26 05:44 UTC, shmel1k commented on internal/app/workerpool/manager.go
> +					fmt.Println("Exiting")
Выглядит как потерянный дебажный принт.

Но, по сути, лучше, чтобы fmt.Println или log.Println не перемешивались в одном проекте.

На 9 строчек ниже уже log.Println

2022-12-26 05:44 UTC, shmel1k commented on internal/app/workerpool/manager.go
> +	once := sync.Once{}
А что будет, если дёрнуть функцию Stop() из миллиона горутин?

2022-12-26 05:44 UTC, shmel1k commented on internal/app/storage/database/postgres.go
> +		log.Printf("Fail when url %s delete %v", id, err)
Лучше вот так:

```go
log.Printf("failed to delete url %q: %s", id, err)
```

2022-12-26 05:44 UTC, shmel1k commented on internal/app/storage/database/postgres.go
> +		log.Println(err)
Тут лучше тоже подробнее ошибку развернуть

2022-12-26 07:03 UTC, BawNer commented on internal/app/config.go
> +	Workers         int
+

2022-12-26 07:04 UTC, BawNer commented on internal/app/handlers/data.go
> +func NewHandler(repository storage.Storage, worker *workerpool.WorkerPool) *Handler {
+

2022-12-26 07:05 UTC, BawNer commented on internal/app/workerpool/manager.go
> +	down    chan struct{}
set stop

2022-12-26 07:05 UTC, BawNer commented on internal/app/workerpool/manager.go
> +		return ErrRepositoryIsClosing
+

2022-12-26 07:06 UTC, BawNer commented on internal/app/workerpool/manager.go
> +					fmt.Println("Exiting")
+

2022-12-26 07:12 UTC, BawNer commented on internal/app/storage/database/postgres.go
> +		log.Println(err)
+

2022-12-26 17:15 UTC, shmel1k requested changes

2022-12-26 17:15 UTC, shmel1k commented on internal/app/handlers/data.go
> +	worker  *workers.WorkerPool
только `workers`

2022-12-26 17:15 UTC, shmel1k commented on internal/app/workers/manager.go
> +	for i := 0; i < countWorkers; i++ {
только лучше `workersCount`: `countWorkers` - это всё же глагол, поэтому тут не подойдёт

2022-12-26 17:15 UTC, shmel1k commented on internal/app/handlers/shortener_test.go
> +			workers.RunWorkers(3)
magic-number 3

Там где-то было про `defaultWorkersCount`

2022-12-26 17:29 UTC, merged